install.packages("dplyr", type = "binary")
install.packages("ggplot2", type = "binary")
install.packages("readxl", type = "binary")
install.packages("plotly", type = "binary")
install.packages("shiny", type = "binary")
install.packages("shinydashboard", type = "binary")
install.packages("shinyShortcut", type = "binary")
install.packages("rvest", type = "binary")
install.packages("tidyr", type = "binary")
install.packages('stringr', type = "binary")
install.packages('zoo', type = "binary")
install.packages('xlsx', type = "binary")
install.packages("doSNOW", type = "binary")
install.packages("foreach", type = "binary")
install.packages("openxlsx", type = "binary")

library(shinyShortcut)
shinyShortcut()
